# Generated by Django 4.2.4 on 2023-11-22 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CreditLoan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kor_co_nm", models.TextField(blank=True, default=-1, null=True)),
                ("fin_co_no", models.TextField(blank=True, default=-1, null=True)),
                ("fin_prdt_cd", models.TextField(blank=True, default=-1, null=True)),
                ("fin_prdt_nm", models.TextField(blank=True, default=-1, null=True)),
                ("join_way", models.TextField(blank=True, default=-1, null=True)),
                ("crdt_prdt_type", models.TextField(blank=True, default=-1, null=True)),
                (
                    "crdt_prdt_type_nm",
                    models.TextField(blank=True, default=-1, null=True),
                ),
                ("dcls_month", models.TextField(blank=True, default=-1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                ("fin_prdt_cd", models.TextField(primary_key=True, serialize=False)),
                ("kor_co_nm", models.TextField(blank=True, default=-1, null=True)),
                ("fin_prdt_nm", models.TextField(blank=True, default=-1, null=True)),
                ("join_way", models.TextField(blank=True, default=-1, null=True)),
                ("loan_inci_expn", models.TextField(blank=True, default=-1, null=True)),
                ("erly_rpay_fee", models.TextField(blank=True, default=-1, null=True)),
                ("dly_rate", models.TextField(blank=True, default=-1, null=True)),
                ("loan_lmt", models.TextField(blank=True, default=-1, null=True)),
                ("dcls_month", models.TextField(blank=True, default=-1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductList",
            fields=[
                ("fin_prdt_cd", models.TextField(primary_key=True, serialize=False)),
                (
                    "product_type",
                    models.IntegerField(blank=True, default=-1, null=True),
                ),
                ("kor_co_nm", models.TextField(blank=True, default=-1, null=True)),
                ("fin_prdt_nm", models.TextField(blank=True, default=-1, null=True)),
                ("etc_note", models.TextField(blank=True, default=-1, null=True)),
                ("join_deny", models.IntegerField(blank=True, default=-1, null=True)),
                ("join_member", models.TextField(blank=True, default=-1, null=True)),
                ("join_way", models.TextField(blank=True, default=-1, null=True)),
                ("spcl_cnd", models.TextField(blank=True, default=-1, null=True)),
                ("dcls_month", models.TextField(blank=True, default=-1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductListOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fin_prdt_cd", models.TextField(blank=True, default=-1, null=True)),
                (
                    "intr_rate_type_nm",
                    models.CharField(blank=True, default=-1, max_length=100, null=True),
                ),
                ("intr_rate", models.FloatField(blank=True, default=-1, null=True)),
                ("intr_rate2", models.FloatField(blank=True, default=-1, null=True)),
                ("save_trm", models.IntegerField(blank=True, default=-1, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.productlist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoanOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mrtg_type", models.TextField(blank=True, default=-1, null=True)),
                ("mrtg_type_nm", models.TextField(blank=True, default=-1, null=True)),
                ("rpay_type", models.TextField(blank=True, default=-1, null=True)),
                ("rpay_type_nm", models.TextField(blank=True, default=-1, null=True)),
                ("lend_rate_type", models.TextField(blank=True, default=-1, null=True)),
                (
                    "lend_rate_type_nm",
                    models.TextField(blank=True, default=-1, null=True),
                ),
                ("lend_rate_min", models.FloatField(blank=True, default=-1, null=True)),
                ("lend_rate_max", models.FloatField(blank=True, default=-1, null=True)),
                ("lend_rate_avg", models.FloatField(blank=True, default=-1, null=True)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="products.loan"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CreditLoanOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fin_co_no", models.TextField(blank=True, default=-1, null=True)),
                (
                    "crdt_lend_rate_type",
                    models.TextField(blank=True, default=-1, null=True),
                ),
                (
                    "crdt_lend_rate_type_nm",
                    models.TextField(blank=True, default=-1, null=True),
                ),
                ("crdt_grad_1", models.FloatField(blank=True, default=-1, null=True)),
                ("crdt_grad_4", models.FloatField(blank=True, default=-1, null=True)),
                ("crdt_grad_5", models.FloatField(blank=True, default=-1, null=True)),
                ("crdt_grad_6", models.FloatField(blank=True, default=-1, null=True)),
                ("crdt_grad_10", models.FloatField(blank=True, default=-1, null=True)),
                ("crdt_grad_11", models.FloatField(blank=True, default=-1, null=True)),
                ("crdt_grad_12", models.FloatField(blank=True, default=-1, null=True)),
                ("crdt_grad_13", models.FloatField(blank=True, default=-1, null=True)),
                ("crdt_grad_avg", models.FloatField(blank=True, default=-1, null=True)),
                (
                    "credit_loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.creditloan",
                    ),
                ),
            ],
        ),
    ]
