# Generated by Django 4.2.4 on 2023-11-17 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductList",
            fields=[
                ("fin_prdt_cd", models.TextField(primary_key=True, serialize=False)),
                (
                    "product_type",
                    models.IntegerField(blank=True, default=-1, null=True),
                ),
                ("kor_co_nm", models.TextField(blank=True, default=-1, null=True)),
                ("fin_prdt_nm", models.TextField(blank=True, default=-1, null=True)),
                ("etc_note", models.TextField(blank=True, default=-1, null=True)),
                ("join_deny", models.IntegerField(blank=True, default=-1, null=True)),
                ("join_member", models.TextField(blank=True, default=-1, null=True)),
                ("join_way", models.TextField(blank=True, default=-1, null=True)),
                ("spcl_cnd", models.TextField(blank=True, default=-1, null=True)),
                ("dcls_month", models.TextField(blank=True, default=-1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductListOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fin_prdt_cd", models.TextField(blank=True, default=-1, null=True)),
                (
                    "intr_rate_type_nm",
                    models.CharField(blank=True, default=-1, max_length=100, null=True),
                ),
                ("intr_rate", models.FloatField(blank=True, default=-1, null=True)),
                ("intr_rate2", models.FloatField(blank=True, default=-1, null=True)),
                ("save_trm", models.IntegerField(blank=True, default=-1, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.productlist",
                    ),
                ),
            ],
        ),
    ]
