# Generated by Django 4.2.4 on 2023-11-22 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
